docker:
  db: {}
domains: []
global:
  name: prompt
  type: app
  version: 13.1.1
test:
  coverage:
    last_report:
      covered: 2774
      excluded: 439
      missing: 2883
      percent: 49.0365918331271
      total: 5657
wex:
  migration: 1
  version: 6.0.112
