docker:
  db: {}
domains: []
global:
  name: prompt
  type: app
  version: 13.1.2
test:
  coverage:
    last_report:
      commit_hash: 580108e8ebdb8b71f2fc7481fd217519c94ef69d
      covered: 2774
      excluded: 439
      missing: 2883
      percent: 49.0365918331271
      total: 5657
wex:
  migration: 1
  version: 6.0.112
